import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/components/componenteRelogio/relogio"; // ⏰ IMPORTANTE

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
//
  const data = new Date();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col justify-start gap-4 p-20 items-center min-h-screen`}
      >

        {/* HEADER */}
        <header className="flex flex-col items-center">
          <h1 className="text-3xl font-bold">React & Next.js</h1>

          <nav>
            <ul className="flex gap-4 list-none m-0 p-0">
              <li><Link href="/">Intro</Link></li>
              <li><Link href="/sobre">Sobre</Link></li>
              <li><Link href="/projetos">Projetos</Link></li>
              <li><Link href="/orgulho">Orgulho</Link></li>
              <li><Link href="/contador">Contador</Link></li>
              <li><Link href="/input">Input</Link></li>
              <li><Link href="/produtos">Produtos</Link></li>
            </ul>
          </nav>
        </header>

        {/* MAIN CONTENT */}
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>

        {/* FOOTER COM RELÓGIO */}
        <footer className="flex items-center gap-4 text-lg">
          <span>DIW {data.getFullYear()}</span>
          <Relogio /> {/* ⏰ Relógio funcionando */}
        </footer>

      </body>
    </html>
  );
}
